production:
  cloud_name: "ddx20vuxl"
  api_key: "182969462325444"
  api_secret: "Bto-ODj7nUQJOnsltOq3SR8xvrw"
  secure: true
  cdn_subdomain: true

development:
  cloud_name: "ddx20vuxl"
  api_key: "182969462325444"
  api_secret: "Bto-ODj7nUQJOnsltOq3SR8xvrw"
  secure: true
  cdn_subdomain: true